### PR TITLE
npm autodeploy

### PR DESCRIPTION
**Pull request by munrocket**
You have really cool minimalistic and tree-shakable library, I like it!

In this PR I add travis config for autopublish. Check this article for additional info.
https://tailordev.fr/blog/2018/03/15/automated-npm-releases-with-travis-ci/

### CODE REVIEW

**Comment by terkelg** [comment]
I don't think this is needed. A CI and auto publish seems to be a bit unnecessary at the moment as there are no unit testing anyway. In fact I personally prefer more granular control over when new versions are released. 

GitHub Actions might be useful in the future for automatically publishing to NPM if we want to go this route – it's simpler and you don't need an additional service as Travis.

**Comment by munrocket** [comment]
Actually it's super easy and handy even without tests, you just change version and your package get published.

**Comment by gordonnl** [comment]
Thanks @munrocket! I think this is a great idea, I do agree with @terkelg however about using Github Actions instead to avoid adding a 3rd party service to keep track of.

I'll update further when I have a chance to dig into Github Actions further.

**Comment by gordonnl** [comment]
From looking into github actions, it seems the obvious choice here. Thanks again for the PR

**Pull request closed without merging**
