### PR TITLE
fix:add fromValues method

### PR DESCRIPTION
**Pull request by todaylg**
function angle rely the function fromValues

### CODE REVIEW

**Comment by gordonnl** [comment]
Hi, thanks for the PR!
I think the expected way to achieve this is:
```
new Vec3([x, y, z]);
```
or
```
new Vec3().set(x, y, z);
```
None of the math/functions classes actually create float32Arrays, they're just used to manipulate them. 
Let me know if this doesn't solve your issue

**Comment by todaylg** [comment]
Hi,Float32Array is a new JavaScript array type in ES2017,no need math/functions classes to create it.

**Comment by gordonnl** [comment]
Yes I'm aware, the Math core classes (Vec2, Vec3, Euler etc) are all extensions of Float32Array.
If you don't want to use the Vec3 class, then you can do:
```javascript
const v = new Float32Array(3);
Vec3Func.set(v, x, y, z);
```
or just simply
```javascript
const v = new Float32Array([x, y, z]);
```
The math function classes (eg Vec3Func) are there to manipulate the arrays, not to create them.

**Comment by todaylg** [comment]
The main problem is not this，Vec3Func‘s function angle(line 572) rely the function fromValues
but no math/functions classes create it
i just add this rely function,copy from gl-matrix

**Pull request closed without merging**
