### PR TITLE
Feature/stencil testing

### PR DESCRIPTION
**Pull request by DougLilliequist**

### CODE REVIEW

**Comment by gordonnl** [comment]
@DougLilliequist Stencil testing changes look great!
It looks like your previous PR changes are mixed in with this one though, which is creating conflicts. Would it be possible to create a PR with just the last two commits? (wrapR & stencil)

**Comment by DougLilliequist** [comment]
@gordonnl Sure thing! I'll have a look after work!

**Comment by DougLilliequist** [comment]
Kapture 2024-12-03 at 10 58 06

Outside of that, it works with both depth testing and depth texture creation when using render targets (as shown in the gif)

As for implementation, here is how one would write to the stencil buffer:

```
const program = new Program(this.gl, {
  vertex,
  fragment,
  depthWrite: false,
  depthTest: false,
 })

program.setStencilFunc(this.gl.ALWAYS, 1, 0xff);
program.setStencilOp(this.gl.KEEP, this.gl.KEEP, this.gl.REPLACE);
```

And here is how an exisiting mesh can test against the stencil buffer. What is neat is that you don't need to make any drastic changes to your exisiting shaders:

```
this.sphere = new SphereMesh(this.gl);
this.sphere.program.setStencilFunc(this.gl.EQUAL, 2, 0xff);
this.sphere.program.setStencilOp(this.gl.KEEP, this.gl.KEEP, this.gl.KEEP);
```

**Comment by DougLilliequist** [comment]
@gordonnl it was a minor merge conflict, let me know if things are looking good (despite the history of previous commits and my failed attempt to wipe the history from this feature branch)

**Comment by pschroen** [comment]
With the usual squash and merge the previous commits will get combined into one commit. 😉

**Comment by DougLilliequist** [comment]
hmmm, closing this pr.

**Pull request closed without merging**
