### PR TITLE
Cylinder geometry support.

### PR DESCRIPTION
**Pull request by ArcaneEngineer**
Interface quite similar to Sphere.js.

Result:

cyl

### CODE REVIEW

**Comment by ArcaneEngineer** [comment]
I left something out. You will need `* height;` at the end of lines 32, 52, and 83 (where, respectively, the two cap centres and radial y positions are), or the `height` param won't work.

**Comment by gordonnl** [comment]
Thanks a lot @ArcaneEngineer. Sorry it took so long.
I'm a little unsure about those UVs on the caps, did you write this code from scratch?
Cheers

**Comment by ArcaneEngineer** [comment]
@gordonnl That's not a very helpful response to something I set up carefully for public use.

If you have a specific issue with how the UVs are setup, please be more specific.

**Comment by ArcaneEngineer** [comment]
Hi @gordonnl, sorry this took so long to respond to, I didn't get notified. Yes I did write that myself. 

Hopefully it provides value for others. Feel free to tag me here if any issues are found with this in future.

**Comment by ArcaneEngineer** [comment]
Why was this never merged?

**Pull request closed without merging**
