### PR TITLE
added Curve

### PR DESCRIPTION
**Pull request by akira-cn**
Try to add CubicBezierCurve 😊.

## Usage

```js
const curve = new CubicBezierCurve({
  p0: new Vec3(0, 0.5, 0),
  p1: new Vec3(0, 1, 1),
  p2: new Vec3(0, -1, 1),
  p3: new Vec3(0, -0.5, 0),
});

const polyline = new Polyline(gl, {
  points: curve.getPoints(20),
  uniforms: {
    uColor: {value: new Color('#f00')},
  }
});
```

### CODE REVIEW

**Comment by gordonnl** [comment]
This is really great @akira-cn, thanks a lot!
I've been meaning to add curve utils for a long time!

One thing I was intending of doing was creating a more general `Curve.js` extra class that would contain different curve algorithms. eg:
```js
const curve = new Curve({
    points: [/* Vec3s */],
    type: 'catmullRom', // or cubicBezier etc
    tension: 0.5, // extra props for different curve types
    closed: false,
});

const points = curve.getPoints(50);
```

What do you think of that approach? The only other curve type that I'd really like implemented is `CatmullRom`, just because it makes creating smooth splines super easy (don't need control points for each segment) - but that can wait though!

**Comment by terkelg** [comment]
Wouldn't two classes be more readable and explicit  – as long as they conform to the same interface. Like `CatmullRomCurve` and `CubicBezierCurve`? I think this would be better for tree-shaking. Would it bee too much repeated code though?

**Comment by gordonnl** [comment]
Yeah, there could be a fair argument there too!
I wouldn't be worried about tree shaking as much as for readability and api simplicity. The point about magic strings (for the `type: 'catmullRom'`) is a really good one though.

In my assumption, each curve algorithm would need their own interpolation function (`getPoint()`), so I guess it depends how long and involved these are. For the example of CubicBezier that @akira-cn has made, it's only 11 LOC, but I think Catmull-Rom is quite a bit more complex.

I'm torn against the need for having to specify the curve type in a string, and duplicated code in multiple files and/or needing to extend a shared `Curve` class, as Threejs does, creating yet more classes.

**Comment by terkelg** [comment]
You could use an `enum` like this
```js
const TYPE = {
  CatmullRom: 1,
  CubicBezier: 2
}
```

Or create a generic class and expose two factory functions. Those alias functions can be standalone or static methods.
```js
const CATMULLROM = 'catmullrom';
const CUBICBEZIER = 'cubicbezier';

class Curve() {
  static CatmullRom(...opts) {
    return new Curve(...opts, CATMULLROM);
  }

  static CubicBezier(...opts) {
    return new Curve(...opts, CUBICBEZIER);
  }

  constructor(gl, a, b, c, type) {
    // ... do whatever
    // if (this.type === CUBICBEZIER) { ... }
  }

  // ... rest of file
}
```

You can avoid magic strings this way without having to add extra classes.
If they differ a lot or you end up with more types of splines I would prefer to subclass.

**Comment by gordonnl** [comment]
Really nice man, I think the factory approach would be a great solve! And I agree that if the file becomes huge or convoluted, separate classes would be better.

**Comment by akira-cn** [comment]
Hi @gordonnl. I've update the pull request based on the discussion above.

**Comment by gordonnl** [comment]
champion! Thanks a lot!

**Comment by firestack** [comment]
Just so it's known, these commits broke Firefox compatibility (didn't check nightly but mainline and developer edition are effected) due to spider monkey not supporting class members yet. 

https://github.com/oframe/ogl/pull/49/commits/c1a952a7d076bc60ef5297f95cf6c22c6b538b9c#diff-681e23deb8a658073098185d98510383R47-R48
Firefox Stack Trace
```
SyntaxError: bad method definition Curve.js:45:9
```

**Comment by akira-cn** [comment]
@firestack Yes. Maybe we should rewrite static class members in this way:

```js
Curve.CATMULLROM = CATMULLROM;
Curve.CUBICBEZIER = CUBICBEZIER;
```

I'll submit another PR soon.

**Pull request merged**
