### PR TITLE
KTXTexture call onUpdate method

### PR DESCRIPTION
**Pull request by akira-cn**
KTXTexture should call `onUpdate` method when parsed buffer.

### CODE REVIEW

**Comment by gordonnl** [comment]
The `Texture` class currently calls `onUpdate` when the texture data is pushed to the GPU via the `texImage2D` call or similar. This still occurs for compressed textures.

Adding the `onUpdate` call to the `KTXTexture` class would cause this to trigger twice - once when parsed, then once when pushed to the GPU, which is not ideal.

What is your use-case for needing a callback at this location?

**Comment by akira-cn** [comment]
I want to update my scene when KTXTexture's image is loaded.

**Comment by gordonnl** [comment]
Ok, I think a better place for the callback you are after would be in the `TextureLoader` class. This is where the files are being loaded, and then processed once loaded. Perhaps an `onLoaded` callback is more what you're after? Would this be accurate?

In the `KTXLoader` class, it expects the buffer to already be loaded, so there is no asynchronous behaviour within the class itself, it just processes the data.

**Comment by akira-cn** [comment]
Would `TextureLoader.load` and `TextureLoader. loadKTX` and `TextureLoader.loadImage` returns a promise?

**Comment by gordonnl** [comment]
`TextureLoader.load` returns the `Texture` instance, however `loadKTX` and `loadImage` could indeed return a promise. Perhaps if this promise was attached to a property on the instance, eg
```
const texture = TextureLoader.load(...);
await texture.loaded;
// Image is now loaded and processed
```

**Comment by gordonnl** [comment]
The promise approach is preferred over `onLoaded` as it can have multiple listeners. An issue currently with `onUpdate` is that it can only have a single callback attached.

**Pull request closed without merging**
